name: Close Project Draft on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  close-draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Close related draft in project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prTitle = context.payload.pull_request.title;

            const { data: projects } = await github.graphql(`
              query {
                viewer {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      title
                      items(first: 50) {
                        nodes {
                          id
                          content {
                            __typename
                            ... on DraftIssue {
                              title
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `);

            for (const project of projects.viewer.projectsV2.nodes) {
              for (const item of project.items.nodes) {
                if (
                  item.content &&
                  item.content.__typename === "DraftIssue" &&
                  item.content.title === prTitle
                ) {
                  await github.graphql(`
                    mutation($projectId: ID!, $itemId: ID!) {
                      deleteProjectV2Item(input: {
                        projectId: $projectId,
                        itemId: $itemId
                      }) {
                        deletedItemId
                      }
                    }
                  `, {
                    projectId: project.id,
                    itemId: item.id
                  });

                  console.log(`Deleted draft "${prTitle}" from project "${project.title}"`);
                }
              }
            }
